### ISSUE TITLE
[프론트 설정] composition-api 추가

### ISSUE THREAD

**Issue by kwonyg** [qhals321/naebook#26]
## TODO
- [x] composition-api 설치

## 기타
- [vue + typescript 환경에서 composition API](https://github.com/MrSung/vue-composition-api-ts-todo)
- [class 스타일 컴포넌트에 composition API 사용법](https://stackoverflow.com/questions/64983076/how-to-use-vue-class-component-with-composition-api-in-vue2-by-typescript)

**Comment by BoMeeYoon** [comment]
오호! 저도 두번째 자료 링크 공유하려고 왔는데 이미 공유가 되어있네요!!!🚀🚀
감사합니다 👍👍👍

**Comment by kwonyg** [comment]
vue3로 변경하면서 필요없어진 이슈
